name: food_fox
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim/Itim-Regular.ttf

    - family: NunitoRegular
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf

    - family: NunitoMedium
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf

    - family: NunitoSemiBold
      fonts:
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf

    - family: NunitoBold
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf

    - family: NunitoItalic
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
          style: italic

    - family: NunitoMediumItalic
      fonts:
        - asset: assets/fonts/Nunito/Nunito-MediumItalic.ttf
          style: italic

    - family: JoshRegular
      fonts:
        - asset: assets/fonts/Josh/Josh-Regular.ttf

    - family: JoshMedium
      fonts:
        - asset: assets/fonts/Josh/Josh-Medium.ttf

    - family: JoshSemiBold
      fonts:
        - asset: assets/fonts/Josh/Josh-SemiBold.ttf

    - family: JoshBold
      fonts:
        - asset: assets/fonts/Josh/Josh-Bold.ttf

    - family: JoshItalic
      fonts:
        - asset: assets/fonts/Josh/Josh-Italic.ttf
          style: italic

    - family: JoshMediumItalic
      fonts:
        - asset: assets/fonts/Josh/Josh-MediumItalic.ttf
          style: italic
